const assert = require('node:assert/strict');
const fs = require('node:fs');
global.window = { location: { hostname: 'demo.github.io' } };
require('../app/workflows.runner.js');
require('../app/topic-research.js');
const runner = window.DPRWorkflowRunner;
const research = window.DPRTopicResearch;
assert.deepEqual(research.__test.englishTerms({ keywords: ['routing', { keyword: 'approximation' }, { keyword: '中文' }, { keyword: 'English中文' }, { keyword: 'disabled', enabled: false }] }), ['routing', 'approximation']);
assert.deepEqual(research.__test.englishTerms({ keywords: [{ keyword: 'RL', query: 'offline reinforcement learning' }] }), ['RL']);
assert.throws(() => runner.sanitizeResearchProfile({ keywords: [{ keyword: 'x'.repeat(1201) }] }));
assert.throws(() => runner.sanitizeResearchProfile({ intent_queries: [{ query: 'x'.repeat(1201) }] }));
assert.throws(() => runner.sanitizeResearchProfile({ constraint_groups: [['x'.repeat(301)]] }));
assert.equal(runner.sanitizeResearchProfile({ description: 'x'.repeat(6000), keywords: [{ keyword_cn: '中'.repeat(6000) }] }).description.length, 6000);
assert.throws(() => runner.sanitizeResearchProfile({ constraint_groups: [['a'], ['b'], ['c'], ['d']] }));
assert.throws(() => runner.sanitizeResearchProfile({ constraint_groups: [Array.from({ length: 9 }, (_, i) => 'term' + i)] }));
assert.throws(() => runner.sanitizeResearchProfile({ constraint_groups: [Array.from({ length: 6 }, (_, i) => 'a' + i), Array.from({ length: 6 }, (_, i) => 'b' + i)] }));
const source = { tag: 'topic', description: 'Routing research', keywords: [{ keyword: 'routing', query: 'routing research', enabled: true, api_key: 'SECRET' }], intent_queries: [{ query: 'routing algorithms', token: 'SECRET' }], api_key: 'SECRET', supabase: { service_role: 'SECRET' } };
const request = runner.buildTopicResearchRequest({ mode: '90', profile: source, as_of: '2026-09-12' });
assert.equal(request.key, 'topic-research');
assert.equal(request.inputs.mode, '90');
assert.equal(request.inputs.content_batch, '10');
assert.ok(!request.inputs.profile_snapshot.includes('SECRET'));
assert.ok(!Object.hasOwn(JSON.parse(request.inputs.profile_snapshot), 'constraint_groups'), 'unrefined snapshots must omit empty constraint groups');
assert.throws(() => runner.sanitizeResearchProfile({ keywords: Array(25).fill('routing') }));
assert.throws(() => runner.sanitizeResearchProfile({ intent_queries: Array(13).fill('routing') }));
assert.ok(!('fetch_days' in request.inputs));
assert.throws(() => runner.buildTopicResearchRequest({ mode: '30', profile: source, as_of: '2026-09-12' }));
const continuation = runner.buildTopicResearchRequest({ action: 'continue-content', run_id: '20260912-abcdef123456', profile: source });
assert.deepEqual(continuation.inputs, { action: 'continue-content', run_id: '20260912-abcdef123456', content_batch: '10' });
assert.throws(() => runner.buildTopicResearchRequest({ action: 'continue-content', run_id: '../bad' }));
assert.ok(research.__test.previewLabel({ status: 'lower_bound', count: 1700 }).includes('至少'));
assert.ok(research.__test.previewLabel({ status: 'partial', count: 100 }).includes('不是全量'));
assert.ok(research.__test.previewLabel({ status: 'unknown' }).includes('不代表没有论文'));
assert.ok(!research.__test.previewLabel({ status: 'partial', count: null }).includes('0 篇'));
assert.ok(!research.__test.previewLabel({ status: 'partial', count: '12' }).includes('12 篇'));
assert.equal(research.__test.previewThreshold({ threshold: 2200 }), 2200);
for (const threshold of [null, '2200', 0, -1, 1.5, Infinity]) assert.equal(research.__test.previewThreshold({ threshold }), 1500);
for (const ack of [undefined, null, false, {}, { ok: false }, { success: false }, { ok: true, status: 'failed' }]) assert.equal(research.__test.dispatchAcknowledged(ack), false);
for (const ack of [true, { ok: true }, { success: true }]) assert.equal(research.__test.dispatchAcknowledged(ack), true);
let previewCount = 0;
let generateCount = 0;
let dispatches = [];
let threshold = 1500;
window.TopicResearchPreview = { preview: async ({ profile }) => { previewCount++; return { status: 'lower_bound', count: 2400, threshold }; } };
let planningDescription = '';
window.SubscriptionsSmartQuery = { generateResearchCandidates: async (_tag, description) => { planningDescription = description; generateCount++; return { keywords: [{ keyword: 'approximation' }], intent_queries: [{ query: 'approximation bounds for routing' }] }; } };
window.confirm = () => true;
runner.runWorkflowByKey = async (key, inputs) => { dispatches.push({ key, inputs }); return true; };
global.fetch = () => { throw new Error('No real network allowed'); };
const nodes = {};
for (const id of ['dpr-topic-start', 'dpr-topic-status', 'dpr-topic-refine', 'dpr-topic-refine-apply', 'dpr-topic-refine-skip', 'dpr-topic-refine-cancel', 'dpr-topic-as-of', 'dpr-topic-refine-text', 'dpr-topic-refine-category', 'dpr-topic-results-entry', 'dpr-topic-results-link']) {
  nodes[id] = { hidden: true, disabled: false, value: '', style: {}, events: {}, addEventListener(type, handler) { this.events[type] = handler; } };
}
nodes['dpr-topic-as-of'].value = '2026-09-12';
nodes['dpr-topic-refine-text'].value = 'Approximation guarantees only';
const root = { querySelector: selector => selector.startsWith('#') ? nodes[selector.slice(1)] : { value: '365' } };
let profiles = [source];
research.mount(root, { getProfiles: () => profiles, getConfig: () => ({}), hasUnsaved: () => false, getConferences: () => [] });
(async () => {
  const fakePreview = window.TopicResearchPreview;
  const actualPreview = require('../app/topic-preview.js');
  actualPreview.__test.clearCache();
  let actualPreviewCalls = 0;
  global.fetch = async () => { actualPreviewCalls++; return { status: 200, headers: { get: () => '0-0/1501' } }; };
  const actualResult = await actualPreview.preview({ profile: JSON.parse(request.inputs.profile_snapshot), mode: '90', asOf: '2026-09-12', config: { supabase_shared: { url: 'https://example.invalid', anon_key: 'sb_publishable_test' } } });
  assert.equal(actualResult.status, 'lower_bound', 'sanitized ordinary profile reaches real preview counting');
  assert.equal(actualResult.count, 1501);
  assert.equal(actualPreviewCalls, 1);
  assert.ok(actualResult.count > actualResult.threshold);
  window.TopicResearchPreview = fakePreview;
  global.fetch = () => { throw new Error('No real network allowed'); };
  await nodes['dpr-topic-start'].events.click();
  assert.equal(previewCount, 1);
  assert.equal(nodes['dpr-topic-refine'].hidden, false);
  assert.equal(dispatches.length, 0);
  await nodes['dpr-topic-start'].events.click();
  assert.equal(previewCount, 1, 'pending refinement does not create another question');
  await nodes['dpr-topic-refine-apply'].events.click();
  assert.equal(previewCount, 2);
  assert.equal(generateCount, 1);
  assert.equal(dispatches.length, 1, 'still >1500 after refinement dispatches without asking again');
  assert.equal(nodes['dpr-topic-results-entry'].hidden, false);
  assert.ok(nodes['dpr-topic-status'].textContent.includes('专题回溯'));
  const snapshot = JSON.parse(dispatches[0].inputs.profile_snapshot);
  assert.deepEqual(snapshot.constraint_groups, [['routing'], ['approximation']]);
  assert.equal(snapshot.refinement, 'Approximation guarantees only');
  assert.equal(source.refinement, undefined, 'daily profile remains untouched');
  assert.ok(snapshot.description.includes('routing algorithms'));
  assert.ok(snapshot.description.includes('routing research'));
  assert.equal(nodes['dpr-topic-refine'].hidden, true);
  await nodes['dpr-topic-start'].events.click();
  await nodes['dpr-topic-refine-skip'].events.click();
  assert.equal(generateCount, 1);
  assert.equal(dispatches.length, 2);
  profiles = [source, { ...source, tag: 'another' }];
  await nodes['dpr-topic-start'].events.click();
  assert.equal(dispatches.length, 2);
  assert.ok(nodes['dpr-topic-status'].textContent.includes('恰好选择一个'));
  profiles = [source];
  threshold = 2500;
  await nodes['dpr-topic-start'].events.click();
  assert.equal(dispatches.length, 3, 'actual configurable threshold controls refinement, not hardcoded 1500');
  assert.equal(nodes['dpr-topic-refine'].hidden, true);
  runner.runWorkflowByKey = async () => undefined;
  await nodes['dpr-topic-start'].events.click();
  assert.ok(nodes['dpr-topic-status'].textContent.includes('未确认工作流已提交'));
  const offline = await research.__test.refineProfile({ tag: 'RL', keywords: [{ keyword: 'RL', query: 'offline reinforcement learning' }], intent_queries: [{ query: 'offline policy evaluation' }] }, 'approximation', 'method');
  assert.deepEqual(offline.constraint_groups, [['RL'], ['approximation']]);
  assert.ok(planningDescription.includes('offline reinforcement learning'));
  assert.ok(planningDescription.includes('offline policy evaluation'));
  assert.ok(planningDescription.includes('仅在原需求内收窄'));
  assert.ok(offline.description.includes('offline reinforcement learning'));
  // 专题独立单选，不得为选定一次任务而改掉日常多选。
  require('../app/subscriptions.manager.js');
  const managerApi = window.SubscriptionsManager.__test;
  const available = [source, { ...source, tag: 'second' }];
  let dailySelection = available.slice();
  let globalSelectionWrites = 0;
  window.SubscriptionsSmartQuery = {
    getSelectedProfilesForRun: () => dailySelection,
    getProfilesForRun: () => available.map((profile, index) => ({ ...profile, id: String(index), selected: dailySelection.includes(profile) })),
    getResearchProfiles: () => available,
    setProfileSelection: () => { globalSelectionWrites++; },
  };
  const picker = { innerHTML: '' };
  managerApi.__setTopicProfilePickerEl(picker);
  managerApi.__resetTopicSelection();
  managerApi.initializeTopicSelection();
  assert.deepEqual(managerApi.getTopicResearchProfiles(), []);
  assert.equal((picker.innerHTML.match(/aria-pressed="true"/g) || []).length, 0);
  managerApi.setTopicProfileSelection('1');
  assert.deepEqual(managerApi.getTopicResearchProfiles().map(profile => profile.tag), ['second']);
  assert.equal((picker.innerHTML.match(/aria-pressed="true"/g) || []).length, 1);
  assert.equal(dailySelection.length, 2);
  assert.equal(globalSelectionWrites, 0);
  managerApi.initializeTopicSelection();
  assert.equal(managerApi.getTopicResearchProfiles()[0].tag, 'second', 'reopening keeps independent topic selection');
  managerApi.__resetTopicSelection();
  dailySelection = [source];
  managerApi.initializeTopicSelection();
  assert.equal(managerApi.getTopicResearchProfiles()[0].tag, source.tag, 'single daily selection is inherited on initialization');
  const manager = fs.readFileSync('app/subscriptions.manager.js', 'utf8');
  assert.ok(manager.includes('dpr-admin-tab-topic'));
  assert.ok(manager.includes('想更深入了解一个研究方向？'));
  assert.ok(!manager.includes('name="dpr-quick-run-mode" value="90"'));
  assert.ok(!manager.includes('id="arxiv-admin-starter-pack-btn"'));
  const index = fs.readFileSync('index.html', 'utf8');
  for (const script of ['topic-preview.js', 'topic-research.js', 'topic-results.js']) assert.ok(index.includes("path: 'app/" + script + "'"));
  console.log('topic research tests passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
